### ISSUE TITLE
Getting error while open fragment second time : SavedStateProvider with the given key is already registered

### ISSUE THREAD

**Issue by nitspatel12** [SimformSolutionsPvtLtd/SSImagePicker#51]
**Describe the bug**
I have implemented this library inside fragment. After exiting  the fragment with back button and open the same fragment and try to open image picker error occur you can find the stacktrace below.

**Additional context**
FATAL EXCEPTION: main
                                                                                                    Process: com.example.evetanhr.debug, PID: 15333
                                                                                                    java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
                                                                                                    	at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.kt:110)
                                                                                                    	at com.app.imagepickerlibrary.util.PickerConfigManager._init_$lambda-0(PickerConfigManager.kt:25)
                                                                                                    	at com.app.imagepickerlibrary.util.PickerConfigManager.$r8$lambda$yxq-75EwC_9xo5MojhV7-4heekM(Unknown Source:0)
                                                                                                    	at com.app.imagepickerlibrary.util.PickerConfigManager$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:4)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
                                                                                                    	at com.app.imagepickerlibrary.util.PickerConfigManager.<init>(PickerConfigManager.kt:22)
                                                                                                    	at com.app.imagepickerlibrary.ImagePicker.<init>(ImagePicker.kt:27)
                                                                                                    	at com.app.imagepickerlibrary.ImagePicker.<init>(Unknown Source:0)
                                                                                                    	at com.app.imagepickerlibrary.ImagePicker$Companion.registerImagePicker(ImagePicker.kt:232)
                                                                                                    	at com.example.evetanhr.view.add.AddEmployeePersonalDetailsFragment.onCreate(AddEmployeePersonalDetailsFragment.kt:66)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7697)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by yashwantgowla-simform** [comment]
@nitspatel12 Thanks for the flagging. We will check the issue and update you soon!

**Comment by priyankj-simform** [comment]
@nitspatel12 Closing the issue as new version **2.1** is released with the fix. Please feel free to reopen this if you still have an issue with the latest version of the library.
