### ISSUE TITLE
GetImagesList "name must not be null"

### ISSUE THREAD

**Issue by amensia** [SimformSolutionsPvtLtd/SSImagePicker#53]
**Describe the bug**
Hello, thanks again for the library, work really well ;)

I have a couple of crash on production linked to Extension.getImageList()
 when name == null

I couldn't reproduce it, just a couple of stacktrace from crqashlytics 

`Fatal Exception: java.lang.NullPointerException: name must not be null
       at com.app.imagepickerlibrary.ExtensionsKt$getImagesList$2.invokeSuspend(Extensions.kt:253)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

I didn't really dig into it, and I don't know how important the name is for a picture, but I was wondering if just avoiding picture if any params of the cursor is null could fix it without creating too many unwanted behavior 

Regards

**Comment by priyankj-simform** [comment]
@amensia Thanks for the stack trace. Will check the issue and update you soon!

**Comment by priyankj-simform** [comment]
@amensia Closing the issue as new version **2.1** is released with the fix. Please feel free to reopen this if you still face the issue with the latest version of the library.
